version: '3.8'

services:
  app-development:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      # target: release
    image: app-development
    # command: python3.6 /code/application_manager.py --docker --config_path /data/supreme/producer/config/config.json --logging_dir /data/supreme/producer/dataset
    command: tail -f  /dev/null
    restart: always
    privileged: true
    network_mode: host
    runtime: nvidia
    volumes:
      - ./:/app/
      - /tmp/:/tmp/
      - /sockets/:/sockets/
    environment:
      # Sets an environment variable to make all NVIDIA devices visible to the container.
      - "NVIDIA_VISIBLE_DEVICES=all"
    logging:
      # Specifies the logging driver
      driver: syslog
      options:
        # Customizes log messages with a tag that includes the container ID, making it easier to identify logs from specific containers.
        tag: "producer_{{.ID}}"
    deploy:
      resources:
        reservations:
          devices:
            # Specifies the driver for device handling, in this case, 'nvidia' for GPU devices.
            - driver: nvidia
              capabilities: [gpu]
